### PR TITLE
added VirtualizedList support

### PR DESCRIPTION
**Pull request by NicolasBonduel**
I'm sorry I didn't add the tests as I'm not familiar with snapshot testing yet.

### CODE REVIEW

**Comment by sospedra** [comment]
If you fix the lintern I'm happy to merge this :)
Probably just with `npm run test:lint -- --fix` is enough

**Comment by sospedra** [comment]
@NicolasBonduel 👀

**Comment by NicolasBonduel** [comment]
I'll take care of that during the weekend if that's alright 😄 
To be completely honest, we ended up not using react-native-dual in our project because it lacks the pull to refresh support.

**Comment by sospedra** [comment]
@NicolasBonduel completely understandable I was in a very busy moment :)

**Pull request closed without merging**
